[package]
name = "hdl-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
logicsim = "0.1.7"
bool-algebra = { git = "https://github.com/eeli1/bool-algebra", version = "0.1.0" }